FROM alpine:3.21

LABEL org.opencontainers.image.source="https://github.com/NovaMachina/containers"
LABEL org.opencontainers.image.description="Short description of this image"

# Install packages
# RUN apk add --no-cache <package>

# Copy files
# COPY rootfs/ /

ENTRYPOINT ["/bin/sh"]
